# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - libgraphviz-dev
    - plantuml
  jobs:
    pre_create_environment:
      # Install rust toolchain for building medrs
      - asdf: plugin-add rust https://github.com/asdf-community/asdf-rust.git
      - asdf: install rust latest
    post_install:
      # Install rust tools
      - cargo: install --version 0.8.0 mdbook
      - cargo: install --version 0.23.0 mdbook-pdf
    post_build:
      # Generate PDF version of docs
      - cargo: run --manifest-path ../Cargo.toml doc --no-deps
      - cp -r ../target/doc ./_build/html/rust-docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
    - path: .
    - extra_requirements:
      - docs

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - htmlzip

# Optional: declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Optional: declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Optional: set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_build:
      - cargo: run --manifest-path ../Cargo.toml doc --no-deps
      - cp -r ../target/doc ./_build/html/rust-docs

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Custom Sphinx configuration
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false